### ISSUE TITLE
Download link Broken

### ISSUE THREAD

**Issue by Dogy06** [facebookresearch/taskmodularnets#3]
The link for wget --show-progress -O data/splits.tar.gz http://www.cs.cmu.edu/~spurushw/projects/compositional/compositional_split_natural.tar.gz
leads to a blank page. Any help would be greatly appreciated.

**Comment by senthilps8** [comment]
The new link is http://www.cs.cmu.edu/~spurushw/publication/compositional/compositional_split_natural.tar.gz
I don't have permissions to make changes to this repository at the moment, but you can checkout #2 for the patch.

**Comment by Dogy06** [comment]
Ah ok, Thanks!

**Comment by e96031413** [comment]
Hi, the download link is now:
[https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz](https://www.senthilpurushwalkam.com/publication/compositional/compositional_split_natural.tar.gz)
